stages:
  - build
  - run

build_develop:
  stage: build
  tags:
    - javafx
  script:
    - git clone -b master https://joao_felipe:gldt-PcMM5sx-x_9KmadeEFDF@gitlab.com/projeto-de-integracao2/backend-integracao.git
    # Builda o backend
    - cd backend-integracao
    - mvn clean install
    - cd ..
    # Builda o front
    - mvn clean package

  only:
      - master

  artifacts:
    paths:
      - target/jfx/native/Projeto_Integracao-1.0.exe
      - backend-integracao/target/Backend_Projeto1-1.0-SNAPSHOT.jar

run_develop:
  stage: run
  tags:
    - javafx
  script:
    - cd backend-integracao/target
    - java -jar Backend_Projeto1-1.0-SNAPSHOT.jar