stages:
  - build

build_develop:
  stage: build
  tags:
    - javafx
  script:
    - ls
    - git clone -b feature/project_four https://joao_felipe:gldt-PcMM5sx-x_9KmadeEFDF@gitlab.com/projeto-de-integracao2/backend-integracao.git
    - ls
    # Builda o backend
    - cd backend-integracao
    - ls
    - mvn clean install
    - cd ..
    - ls
    - cd ..
    - ls
    # Builda o front
    - mvn clean package

  only:
      - feature/project_four

  artifacts:
    paths:
      - target/jfx/native/Projeto_Integracao-1.0.exe